// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	server2 "go-sample/internal/server"
	"go-sample/pkg/server"
)

// Injectors from wire.go:

func InitializeApp() (*server.App, func(), error) {
	engine := server2.NewGinServer()
	tools := NewTools()
	grpcServer := server2.NewGRPCServer()
	app, err := NewApp(engine, tools, grpcServer)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
	}, nil
}
