// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

func InitializeApp() (*GinServerApp, func(), error) {
	engine := NewGinServer()
	tools := NewAllTools()
	ginServerApp, err := NewGinServerApp(engine, tools)
	if err != nil {
		return nil, nil, err
	}
	return ginServerApp, func() {
	}, nil
}
